name: KChat
version: ${project.version}
main: com.kaleydra.kchat.KChat
depend: [LiCETIA, KRPG, Towny, Vault, Essentials]
commands:
    townchat:
        help: switches between town chat and global. You can send single messages via /<command> <message>
        usage: /<command> (message)
        aliases: [tc]
        permission: kchat.switch.townchat
    globalchat:
        help: switches to global. You can send single messages via /<command> <message>
        usage: /<command>
        aliases: [g,global]
        permission: kchat.switch.globalchat
    kchat:
        help: ""
        permission: kchat.admin